const posts = [
  {
    title: "Blog Post 1", synopsis: " Lorem ipsum odor amet, consectetuer adipiscing elit. Mi integer purus scelerisque, congue phasellus fusce. Nulla malesuada dictum phasellus in elit tempus fames. Enim odio tempor platea eros amet ex? Mauris accumsan primis mus; litora sapien iaculis ridiculus. Consequat volutpat arcu eget massa; pretium tristique porta. Dolor integer facilisis nec nibh at. ", date: Date.now(), url: "/blogs/1.html"
  },
  {
    title: "Blog Post 2", synopsis: " Id torquent adipiscing ultrices imperdiet curabitur facilisi arcu. Pellentesque at ultricies ridiculus ornare duis risus accumsan cursus. Litora eu quam nibh nibh; vivamus ligula imperdiet urna libero. Justo ullamcorper placerat posuere mollis platea. Felis dignissim primis auctor nascetur rutrum. Eget ultrices dictumst eu etiam augue facilisis. Purus magnis pharetra ultrices imperdiet habitant condimentum quisque. Sodales ad finibus ut sapien quis amet. Feugiat justo enim lobortis, consectetur faucibus senectus convallis. Senectus fusce dignissim habitasse metus; nullam nunc tellus. Varius aenean senectus parturient; vitae tempus cursus. Tortor luctus etiam ut sit elementum ridiculus? Consequat facilisi dictumst, lacinia imperdiet dictum turpis magna accumsan. Curae auctor ex parturient sociosqu blandit quis. ", date: Date.now(), url: "/blogs/2.html"
  },
  {
    title: "Blog Post 3", synopsis: " Lorem ipsum odor amet, consectetuer adipiscing elit. Mi integer purus scelerisque, congue phasellus fusce. Nulla malesuada dictum phasellus in elit tempus fames. Enim odio tempor platea eros amet ex? Mauris accumsan primis mus; litora sapien iaculis ridiculus. Consequat volutpat arcu eget massa; pretium tristique porta. Dolor integer facilisis nec nibh at. Nisi parturient dolor rutrum netus magna eros proin ultrices lacinia. Luctus curabitur lacinia rutrum hac erat magna a gravida. Tempus eu neque integer leo conubia ornare felis dictumst. Eget rhoncus pretium aptent dignissim sociosqu pellentesque egestas aliquam. Ex posuere adipiscing cras blandit magnis urna. Netus mi senectus nullam suspendisse odio. Proin iaculis semper gravida nec, semper magna cubilia feugiat. Ullamcorper pharetra porta tortor nec vulputate sit? Sit at augue nec ac vehicula aptent semper. Auctor sit taciti platea netus consequat condimentum. Mauris sagittis natoque natoque dis tortor ultricies. Litora nascetur nisi sapien nullam magna iaculis pharetra. Ex luctus fusce donec justo congue tortor primis. Aliquet class magnis magnis tincidunt, gravida nam. ", date: Date.now(), url: "/blogs/3.html"
  }
]
